---
title: "Ideas"
output: html_notebook
---


Abstract


Plant pollinator intaractions are a keystone process for ecosystem functioning. However, we lack comprehensive information from both plants and pollinators that can inform from this mutualistic interaction worldwide. In order to tackle this, we have selected 30 networks distributed across the world and looked for key floral traits of plant-pollinator interactions for a total of 1600 species. Here we look how these floral traits shape the different plant-pollinator networks and the main fuctional groups of insect pollinating species. Giving the different nature of the data collated we do not compare across networks and we focus on the main general patterns/results within network. We have conducted our analysis at 3 levels, 1) unique networks, 2) metawebs and by 3) grouping both. We find that specific traits are associated with different guilds of floral visitors within these networks. 
We also highlight the lack of information about traits and the reproductive biology of the plant species of these networks. Our work shows the importance of deepen in species traits in order to understand key processes that can be seen with network metrics and highlights the importance of elemental ecology for species conservation.



Hypothesis





#How to proceed

- Select main floral traits

1) Flower size

2) Fower shape

3) Compatibility system

4) Style length/Ovule number

5) Selfing level

- Plot taxa/traits Barplot?

Y axis Spp richness? X Axis the grouping variables? 

Consider Poll taxa here with more developped plots?

- Hypothesis

 1) Do we have matching between specific taxa and grouping traits? Maybe show this with likelihood of visitation
    1.1 Are selfers/self compatible species less relevant in the network? How can we interpretate that (generalist vs specialization/connectance) We expect less dependency on pollinators...


1.2 

 2) 

 3) Possibility of testing redundancy with phylogeny
 
 - How to group Poll taxa. 
 
 What to do with non-insects?
 
 
 