---
header-includes:
    - \usepackage{setspace}\doublespacing
output:
  pdf_document: default
  html_document: default
---


\setlength{\abovedisplayskip}{25pt}
\setlength{\belowdisplayskip}{25pt}
\setlength{\abovedisplayshortskip}{25pt}
\setlength{\belowdisplayshortskip}{25pt}

```{r, echo = F}
library(knitr)
knitr::opts_chunk$set(message = FALSE)

if(is_latex_output()) {
  plot_default <- knit_hooks$get("plot")
  knit_hooks$set(plot = function(x, options) { 
    x <- c(plot_default(x, options), "\\vspace{25pt}")
  })
}
```

#TRAIT CORRELOGRAM

```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
library(brms)
library(ggplot2)
library(tidybayes)
library(tidyverse)
library(kableExtra)


setwd("~/R_Projects/Reproductive traits") 
merged_all_2 <- read.csv("Data/Csv/long_all.csv")

library(qad)

#qad
floral_1<-merged_all_2[c("Visits", "z_score","Corolla_length_mean","Floral_unit_width","style_length_mm", "Autonomous_selfing_level_fruit_set","ovules_mean","plant_height_mean_m")]
model <- pairwise.qad(floral_1, permutation = FALSE)
heatmap.qad(model, select = "dependence", fontsize = 5, significance = TRUE, sign.level = 0.05)



```

#PCA ALL QUATITATIVE NO AUTONOMOUS SELFING

```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
library(brms)
library(ggplot2)
library(tidybayes)
library(tidyverse)
library(kableExtra)


setwd("~/R_Projects/Reproductive traits") 
merged_all_2 <- read.csv("Data/Csv/long_all.csv")


library("FactoMineR")
library("factoextra")
floral_1<-merged_all_2[c("z_score","Floral_unit_width","style_length_mm", "ovules_mean","plant_height_mean_m")]
floral_1[,c(1:5)] <- scale(mutate_all(floral_1[,c(1:5)], function(x) as.numeric(as.character(x))))
res.pca <- PCA(floral_1, graph = FALSE)
fviz_pca_biplot(res.pca, label ="var", col.ind="cos2",repel = TRUE,col.var = "cos2",ellipse.level=0.95,gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07")) +
  theme_minimal()+ylim(-5,10)+xlim(-5,15)
```

#PCA ALL QUATITATIVE WITH AUTONOMOUS SELFING (We loss many points)


```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
library(brms)
library(ggplot2)
library(tidybayes)
library(tidyverse)
library(kableExtra)


setwd("~/R_Projects/Reproductive traits") 
merged_all_2 <- read.csv("Data/Csv/long_all.csv")


library("FactoMineR")
library("factoextra")
floral_1<-merged_all_2[c("Id", "z_score","Autonomous_selfing_level_fruit_set","Floral_unit_width","style_length_mm", "ovules_mean","plant_height_mean_m")]
res.pca <- PCA(na.omit(mutate_all(floral_1[-1], function(x) as.numeric(as.character(x)))), graph = FALSE)
fviz_pca_biplot(res.pca, label ="var", col.ind="cos2",repel = TRUE,col.var = "cos2",ellipse.level=0.95,gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07")) +
  theme_minimal()+ylim(-5,10)+xlim(-5,15)
```

