---
header-includes:
    - \usepackage{setspace}\doublespacing
output:
  pdf_document: default
  html_document: default
---


\setlength{\abovedisplayskip}{25pt}
\setlength{\belowdisplayskip}{25pt}
\setlength{\abovedisplayshortskip}{25pt}
\setlength{\belowdisplayshortskip}{25pt}

```{r, echo = F}
library(knitr)
knitr::opts_chunk$set(message = FALSE)

if(is_latex_output()) {
  plot_default <- knit_hooks$get("plot")
  knit_hooks$set(plot = function(x, options) { 
    x <- c(plot_default(x, options), "\\vspace{25pt}")
  })
}
```


# PCA QUANTITATIVE DATA-SELFING LEVEL

```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
#LOAD LIBRARIES
library(readxl) #read excel file (trait data)
library(dplyr) #data manipulation
library(missMDA) #For missing values
library(FactoMineR) #Produce pca biplot with individuals and variables
library(factoextra)
library(ggpubr)

#change working directory
setwd("~/R_Projects/Reproductive traits") 

#LOAD DATA
trait_data <- read_excel("Data/Trait_data_raw/Trait_data_final.xlsx",na = "NA")
#select just filled rows
trait_data_1 <- trait_data[1:1701,]
#filter data, select species with flower level info and capitulum
trait_filtered <- filter(trait_data_1, Info_level == "flower" |  Info_level == "capitulum")
levels(as.factor(trait_filtered$Info_level))
#select columns of interest
traits <- trait_filtered %>% select(Order_all,Family_all,Genus_all,Species_all,Breeding_system,IMPUTED_Compatibility,Autonomous_selfing_level,Autonomous_selfing_level_data_type,Autonomous_selfing_level_fruit_set,Flower_morphology,Flower_symmetry,Flowers_per_plant,Flowers_per_inflorescence,Floral_unit_width,Corolla_diameter_mean,Corolla_length_mean,STYLE_IMPUTED,OVULES_IMPUTED,life_form,lifespan,IMPUTED_plant_height_mean_m)
#Remove duplicated species
t <- traits[!duplicated(traits$Species_all), ]
#check structure of the data
str(t)
#remove cases where the species is NA 
t <- t[!is.na(t$Species_all), ]

str(t)
t_trial <- t[,c(5,6,7,9:21)]
str(t_trial)
cols <- c( "Breeding_system","IMPUTED_Compatibility", "Autonomous_selfing_level","Flower_morphology","Flower_symmetry", "life_form", "lifespan")

t_trial[cols] <- lapply(t_trial[cols], factor)  ## as.factor() could also be used

colnames(t_trial) <- c("Breeding system","Compatibility system","Selfing_level", "Quantitative selfing","Flower morphology","Flower symmetry",  "Flower/plant", "Flower/inflorescence", "Inflorescence width", "Flower width",  "Flower length",  "Style length", "Ovule number", "Life form","Life span", "Plant height")

str(t_trial$`Life form`)
t_trial$Selfing_level<- as.factor(t_trial$Selfing_level)
res.impute <- imputeFAMD(t_trial, ncp=3,threshold = 1e-06) 


res.impute$completeObs$Selfing_level <- factor(res.impute$completeObs$Selfing_level, levels = c("high", "medium", "low", "none"))

#from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
fviz_pca_biplot(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(3)], 
                pointshape = 19, pointsize = 1,
                palette = c("#FDE725FF","#31688EFF","#440154FF", "#35B779FF"),
                # Variables
                col.var = "black",title="",  arrowsize = 0.6,alpha.var=0.7)+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Selfing")



res.impute$completeObs$Selfing_level <- as.character(res.impute$completeObs$Selfing_level)
res.impute$completeObs$Selfing_level[res.impute$completeObs$Selfing_level=="high"] <- "selfer"
res.impute$completeObs$Selfing_level[res.impute$completeObs$Selfing_level=="medium"] <- "selfer"
res.impute$completeObs$Selfing_level[res.impute$completeObs$Selfing_level=="low"] <- "non_selfer"
res.impute$completeObs$Selfing_level[res.impute$completeObs$Selfing_level=="none"] <- "non_selfer"
res.impute$completeObs$Selfing_level <- as.factor(res.impute$completeObs$Selfing_level)


#from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
fviz_pca_biplot(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(3)], 
                pointshape = 19, pointsize = 1,
                palette = c("#35B779FF","#FDE725FF"),
                # Variables
                col.var = "black",title="",  arrowsize = 0.6,alpha.var=0.7)+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Selfing")


```


#LIFE FORM


```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
#LOAD LIBRARIES
library(readxl) #read excel file (trait data)
library(dplyr) #data manipulation
library(missMDA) #For missing values
library(FactoMineR) #Produce pca biplot with individuals and variables
library(factoextra)
library(ggpubr)

#change working directory
setwd("~/R_Projects/Reproductive traits") 

#LOAD DATA
trait_data <- read_excel("Data/Trait_data_raw/Trait_data_final.xlsx",na = "NA")
#select just filled rows
trait_data_1 <- trait_data[1:1701,]
#filter data, select species with flower level info and capitulum
trait_filtered <- filter(trait_data_1, Info_level == "flower" |  Info_level == "capitulum")
levels(as.factor(trait_filtered$Info_level))
#select columns of interest
traits <- trait_filtered %>% select(Order_all,Family_all,Genus_all,Species_all,Breeding_system,IMPUTED_Compatibility,Autonomous_selfing_level,Autonomous_selfing_level_data_type,Autonomous_selfing_level_fruit_set,Flower_morphology,Flower_symmetry,Flowers_per_plant,Flowers_per_inflorescence,Floral_unit_width,Corolla_diameter_mean,Corolla_length_mean,STYLE_IMPUTED,OVULES_IMPUTED,life_form,lifespan,IMPUTED_plant_height_mean_m)
#Remove duplicated species
t <- traits[!duplicated(traits$Species_all), ]
#check structure of the data
str(t)
#remove cases where the species is NA 
t <- t[!is.na(t$Species_all), ]

str(t)
t_trial <- t[,c(5,6,7,9:21)]
str(t_trial)
cols <- c( "Breeding_system","IMPUTED_Compatibility", "Autonomous_selfing_level","Flower_morphology","Flower_symmetry", "life_form", "lifespan")

t_trial[cols] <- lapply(t_trial[cols], factor)  ## as.factor() could also be used

colnames(t_trial) <- c("Breeding system","Compatibility system","Selfing_level", "Quantitative selfing","Flower morphology","Flower symmetry",  "Flower/plant", "Flower/inflorescence", "Inflorescence width", "Flower width",  "Flower length",  "Style length", "Ovule number", "Life form","Life span", "Plant height")

str(t_trial$`Life form`)
t_trial$Selfing_level<- as.factor(t_trial$Selfing_level)
res.impute <- imputeFAMD(t_trial, ncp=3,threshold = 1e-06) 


res.impute$completeObs$Selfing_level <- factor(res.impute$completeObs$Selfing_level, levels = c("high", "medium", "low", "none"))

#from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
fviz_pca_biplot(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(14)], 
                pointshape = 19, pointsize = 1,
                palette = c("#FDE725FF","#31688EFF","#440154FF", "#35B779FF"),
                # Variables
                col.var = "black",title="",  arrowsize = 0.6,alpha.var=0.7)+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Life form")

```


# COMPATIBILITY


```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
#LOAD LIBRARIES
library(readxl) #read excel file (trait data)
library(dplyr) #data manipulation
library(missMDA) #For missing values
library(FactoMineR) #Produce pca biplot with individuals and variables
library(factoextra)
library(ggpubr)

#change working directory
setwd("~/R_Projects/Reproductive traits") 

#LOAD DATA
trait_data <- read_excel("Data/Trait_data_raw/Trait_data_final.xlsx",na = "NA")
#select just filled rows
trait_data_1 <- trait_data[1:1701,]
#filter data, select species with flower level info and capitulum
trait_filtered <- filter(trait_data_1, Info_level == "flower" |  Info_level == "capitulum")
levels(as.factor(trait_filtered$Info_level))
#select columns of interest
traits <- trait_filtered %>% select(Order_all,Family_all,Genus_all,Species_all,Breeding_system,IMPUTED_Compatibility,Autonomous_selfing_level,Autonomous_selfing_level_data_type,Autonomous_selfing_level_fruit_set,Flower_morphology,Flower_symmetry,Flowers_per_plant,Flowers_per_inflorescence,Floral_unit_width,Corolla_diameter_mean,Corolla_length_mean,STYLE_IMPUTED,OVULES_IMPUTED,life_form,lifespan,IMPUTED_plant_height_mean_m)
#Remove duplicated species
t <- traits[!duplicated(traits$Species_all), ]
#check structure of the data
str(t)
#remove cases where the species is NA 
t <- t[!is.na(t$Species_all), ]

str(t)
t_trial <- t[,c(5,6,7,9:21)]
str(t_trial)
cols <- c( "Breeding_system","IMPUTED_Compatibility", "Autonomous_selfing_level","Flower_morphology","Flower_symmetry", "life_form", "lifespan")

t_trial[cols] <- lapply(t_trial[cols], factor)  ## as.factor() could also be used

colnames(t_trial) <- c("Breeding system","Compatibility system","Selfing_level", "Quantitative selfing","Flower morphology","Flower symmetry",  "Flower/plant", "Flower/inflorescence", "Inflorescence width", "Flower width",  "Flower length",  "Style length", "Ovule number", "Life form","Life span", "Plant height")

res.impute <- imputeFAMD(t_trial, ncp=3,threshold = 1e-06) 
levels( res.impute$completeObs$IMPUTED_Compatibility)

  res.impute$completeObs$`Compatibility system` <- as.character(res.impute$completeObs$`Compatibility system`)
 res.impute$completeObs$`Compatibility system` <-  gsub("Compatibility system_", "", res.impute$completeObs$`Compatibility system`)

res.impute$completeObs$`Compatibility system` <- factor(res.impute$completeObs$`Compatibility system`, levels = c("self_compatible", "partially_self_compatible","self_incompatible", "monoecious", "dioecious"))

 
 #from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
fviz_pca_biplot(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(2)], 
                pointshape = 19, pointsize = 1,
                palette = c("#FDE725FF","#31688EFF","#440154FF", "#35B779FF","#21908CFF"),
                # Variables
                col.var = "black",title="",  arrowsize = 0.6,alpha.var=0.7)+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Compatibility")

```


#Life span


```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
#LOAD LIBRARIES
library(readxl) #read excel file (trait data)
library(dplyr) #data manipulation
library(missMDA) #For missing values
library(FactoMineR) #Produce pca biplot with individuals and variables
library(factoextra)
library(ggpubr)

#change working directory
setwd("~/R_Projects/Reproductive traits") 

#LOAD DATA
trait_data <- read_excel("Data/Trait_data_raw/Trait_data_final.xlsx",na = "NA")
#select just filled rows
trait_data_1 <- trait_data[1:1701,]
#filter data, select species with flower level info and capitulum
trait_filtered <- filter(trait_data_1, Info_level == "flower" |  Info_level == "capitulum")
levels(as.factor(trait_filtered$Info_level))
#select columns of interest
traits <- trait_filtered %>% select(Order_all,Family_all,Genus_all,Species_all,Breeding_system,IMPUTED_Compatibility,Autonomous_selfing_level,Autonomous_selfing_level_data_type,Autonomous_selfing_level_fruit_set,Flower_morphology,Flower_symmetry,Flowers_per_plant,Flowers_per_inflorescence,Floral_unit_width,Corolla_diameter_mean,Corolla_length_mean,STYLE_IMPUTED,OVULES_IMPUTED,life_form,lifespan,IMPUTED_plant_height_mean_m)
#Remove duplicated species
t <- traits[!duplicated(traits$Species_all), ]
#check structure of the data
str(t)
#remove cases where the species is NA 
t <- t[!is.na(t$Species_all), ]

str(t)
t_trial <- t[,c(5,6,7,9:21)]
str(t_trial)
cols <- c( "Breeding_system","IMPUTED_Compatibility", "Autonomous_selfing_level","Flower_morphology","Flower_symmetry", "life_form", "lifespan")

t_trial[cols] <- lapply(t_trial[cols], factor)  ## as.factor() could also be used

colnames(t_trial) <- c("Breeding system","Compatibility system","Selfing_level", "Quantitative selfing","Flower morphology","Flower symmetry",  "Flower/plant", "Flower/inflorescence", "Inflorescence width", "Flower width",  "Flower length",  "Style length", "Ovule number", "Life form","Life span", "Plant height")

res.impute <- imputeFAMD(t_trial, ncp=3,threshold = 1e-06) 

res.impute$completeObs$`Life span` <- as.character(res.impute$completeObs$`Life span`)
res.impute$completeObs$`Life span`[res.impute$completeObs$`Life span`=="annual"] <- "short_lived"
res.impute$completeObs$`Life span`[res.impute$completeObs$`Life span`=="biennial"] <- "short_lived"
res.impute$completeObs$`Life span` <- as.factor(res.impute$completeObs$`Life span`)

 
 #from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
fviz_pca_biplot(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(15)], 
                pointshape = 19, pointsize = 1,
                palette = c("#35B779FF","#FDE725FF"),
                # Variables
                col.var = "black",title="",  arrowsize = 0.6,alpha.var=0.7)+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Life span")


```


#Symmetry


```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
#LOAD LIBRARIES
library(readxl) #read excel file (trait data)
library(dplyr) #data manipulation
library(missMDA) #For missing values
library(FactoMineR) #Produce pca biplot with individuals and variables
library(factoextra)
library(ggpubr)

#change working directory
setwd("~/R_Projects/Reproductive traits") 

#LOAD DATA
trait_data <- read_excel("Data/Trait_data_raw/Trait_data_final.xlsx",na = "NA")
#select just filled rows
trait_data_1 <- trait_data[1:1701,]
#filter data, select species with flower level info and capitulum
trait_filtered <- filter(trait_data_1, Info_level == "flower" |  Info_level == "capitulum")
levels(as.factor(trait_filtered$Info_level))
#select columns of interest
traits <- trait_filtered %>% select(Order_all,Family_all,Genus_all,Species_all,Breeding_system,IMPUTED_Compatibility,Autonomous_selfing_level,Autonomous_selfing_level_data_type,Autonomous_selfing_level_fruit_set,Flower_morphology,Flower_symmetry,Flowers_per_plant,Flowers_per_inflorescence,Floral_unit_width,Corolla_diameter_mean,Corolla_length_mean,STYLE_IMPUTED,OVULES_IMPUTED,life_form,lifespan,IMPUTED_plant_height_mean_m)
#Remove duplicated species
t <- traits[!duplicated(traits$Species_all), ]
#check structure of the data
str(t)
#remove cases where the species is NA 
t <- t[!is.na(t$Species_all), ]

str(t)
t_trial <- t[,c(5,6,7,9:21)]
str(t_trial)
cols <- c( "Breeding_system","IMPUTED_Compatibility", "Autonomous_selfing_level","Flower_morphology","Flower_symmetry", "life_form", "lifespan")

t_trial[cols] <- lapply(t_trial[cols], factor)  ## as.factor() could also be used

colnames(t_trial) <- c("Breeding system","Compatibility system","Selfing_level", "Quantitative selfing","Flower morphology","Flower symmetry",  "Flower/plant", "Flower/inflorescence", "Inflorescence width", "Flower width",  "Flower length",  "Style length", "Ovule number", "Life form","Life span", "Plant height")

res.impute <- imputeFAMD(t_trial, ncp=3,threshold = 1e-06) 


 #from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
fviz_pca_biplot(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(6)], 
                pointshape = 19, pointsize = 1,
                palette = c("#35B779FF","#FDE725FF"),
                # Variables
                col.var = "black",title="",  arrowsize = 0.6,alpha.var=0.7)+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Symmetry")


```

#Flower morphology


```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
#LOAD LIBRARIES
library(readxl) #read excel file (trait data)
library(dplyr) #data manipulation
library(missMDA) #For missing values
library(FactoMineR) #Produce pca biplot with individuals and variables
library(factoextra)
library(ggpubr)

#change working directory
setwd("~/R_Projects/Reproductive traits") 

#LOAD DATA
trait_data <- read_excel("Data/Trait_data_raw/Trait_data_final.xlsx",na = "NA")
#select just filled rows
trait_data_1 <- trait_data[1:1701,]
#filter data, select species with flower level info and capitulum
trait_filtered <- filter(trait_data_1, Info_level == "flower" |  Info_level == "capitulum")
levels(as.factor(trait_filtered$Info_level))
#select columns of interest
traits <- trait_filtered %>% select(Order_all,Family_all,Genus_all,Species_all,Breeding_system,IMPUTED_Compatibility,Autonomous_selfing_level,Autonomous_selfing_level_data_type,Autonomous_selfing_level_fruit_set,Flower_morphology,Flower_symmetry,Flowers_per_plant,Flowers_per_inflorescence,Floral_unit_width,Corolla_diameter_mean,Corolla_length_mean,STYLE_IMPUTED,OVULES_IMPUTED,life_form,lifespan,IMPUTED_plant_height_mean_m)
#Remove duplicated species
t <- traits[!duplicated(traits$Species_all), ]
#check structure of the data
str(t)
#remove cases where the species is NA 
t <- t[!is.na(t$Species_all), ]

str(t)
t_trial <- t[,c(5,6,7,9:21)]
str(t_trial)
cols <- c( "Breeding_system","IMPUTED_Compatibility", "Autonomous_selfing_level","Flower_morphology","Flower_symmetry", "life_form", "lifespan")

t_trial[cols] <- lapply(t_trial[cols], factor)  ## as.factor() could also be used

colnames(t_trial) <- c("Breeding system","Compatibility system","Selfing_level", "Quantitative selfing","Flower morphology","Flower symmetry",  "Flower/plant", "Flower/inflorescence", "Inflorescence width", "Flower width",  "Flower length",  "Style length", "Ovule number", "Life form","Life span", "Plant height")

res.impute <- imputeFAMD(t_trial, ncp=3,threshold = 1e-06) 


res.impute$completeObs$`Flower morphology` <- as.character(res.impute$completeObs$`Flower morphology`)
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="bowl"] <- "open"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="dish"] <- "open"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="exposed"] <- "open"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="spadix"] <- "spike"

res.impute$completeObs$`Flower morphology` <- as.factor(res.impute$completeObs$`Flower morphology`)


 #from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
fviz_pca_biplot(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(5)], 
                pointshape = 19, pointsize = 1,
                palette = c("#440154FF", "#46337EFF", "#365C8DFF", "#277F8EFF", "#1FA187FF", "#4AC16DFF", "#9FDA3AFF", "#FDE725FF"),
                # Variables
                col.var = "black",title="",  arrowsize = 0.6,alpha.var=0.7)+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Flower shape")


```


#Breeding system


```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
#LOAD LIBRARIES
library(readxl) #read excel file (trait data)
library(dplyr) #data manipulation
library(missMDA) #For missing values
library(FactoMineR) #Produce pca biplot with individuals and variables
library(factoextra)
library(ggpubr)

#change working directory
setwd("~/R_Projects/Reproductive traits") 

#LOAD DATA
trait_data <- read_excel("Data/Trait_data_raw/Trait_data_final.xlsx",na = "NA")
#select just filled rows
trait_data_1 <- trait_data[1:1701,]
#filter data, select species with flower level info and capitulum
trait_filtered <- filter(trait_data_1, Info_level == "flower" |  Info_level == "capitulum")
levels(as.factor(trait_filtered$Info_level))
#select columns of interest
traits <- trait_filtered %>% select(Order_all,Family_all,Genus_all,Species_all,Breeding_system,IMPUTED_Compatibility,Autonomous_selfing_level,Autonomous_selfing_level_data_type,Autonomous_selfing_level_fruit_set,Flower_morphology,Flower_symmetry,Flowers_per_plant,Flowers_per_inflorescence,Floral_unit_width,Corolla_diameter_mean,Corolla_length_mean,STYLE_IMPUTED,OVULES_IMPUTED,life_form,lifespan,IMPUTED_plant_height_mean_m)
#Remove duplicated species
t <- traits[!duplicated(traits$Species_all), ]
#check structure of the data
str(t)
#remove cases where the species is NA 
t <- t[!is.na(t$Species_all), ]

str(t)
t_trial <- t[,c(5,6,7,9:21)]
str(t_trial)
cols <- c( "Breeding_system","IMPUTED_Compatibility", "Autonomous_selfing_level","Flower_morphology","Flower_symmetry", "life_form", "lifespan")

t_trial[cols] <- lapply(t_trial[cols], factor)  ## as.factor() could also be used

colnames(t_trial) <- c("Breeding system","Compatibility system","Selfing_level", "Quantitative selfing","Flower morphology","Flower symmetry",  "Flower/plant", "Flower/inflorescence", "Inflorescence width", "Flower width",  "Flower length",  "Style length", "Ovule number", "Life form","Life span", "Plant height")

res.impute <- imputeFAMD(t_trial, ncp=3,threshold = 1e-06) 

res.impute$completeObs$`Breeding system` <- as.character(res.impute$completeObs$`Breeding system`)
res.impute$completeObs$`Breeding system` <- gsub("Breeding system_","", res.impute$completeObs$`Breeding system`)
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="androdioecious"] <- "dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="androgynodioecious"] <- "dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="andromonoecious"] <- "monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="gynodioecious"] <- "dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="gynoecious"] <- "monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="gynomonoecious"] <- "monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="gynomonoecious"] <- "monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="monoecious_dioecious"] <- "monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="polygamo-dioecious"] <- "dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="protandrous"] <- "hermaphrodite"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="protogynous"] <- "hermaphrodite"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="subdioecious"] <- "dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="submonoecious"] <- "monoecious"
res.impute$completeObs$`Breeding system` <- as.factor(res.impute$completeObs$`Breeding system`)


 #from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
fviz_pca_biplot(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(1)], 
                pointshape = 19, pointsize = 1,
                palette = c("#440154FF", "#21908CFF", "#FDE725FF"),
                # Variables
                col.var = "black",title="",  arrowsize = 0.6,alpha.var=0.7)+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Breeding system")

levels(res.impute$completeObs$Breeding_system)

```


