---
header-includes:
    - \usepackage{setspace}\doublespacing
output:
  pdf_document: default
  html_document: default
---


\setlength{\abovedisplayskip}{25pt}
\setlength{\belowdisplayskip}{25pt}
\setlength{\abovedisplayshortskip}{25pt}
\setlength{\belowdisplayshortskip}{25pt}

```{r, echo = F}
library(knitr)
knitr::opts_chunk$set(message = FALSE)

if(is_latex_output()) {
  plot_default <- knit_hooks$get("plot")
  knit_hooks$set(plot = function(x, options) { 
    x <- c(plot_default(x, options), "\\vspace{25pt}")
  })
}
```


#PCA by individuals and coloured by qualitative variables

```{r, echo=FALSE, message=FALSE, cache=FALSE, results='hide', warning=FALSE, fig.width=9, fig.height=9, fig.align='center'}
#LOAD LIBRARIES
library(readxl) #read excel file (trait data)
library(dplyr) #data manipulation
library(missMDA) #For missing values
library(FactoMineR) #Produce pca biplot with individuals and variables
library(factoextra)
library(ggpubr)
library(cowplot)
library(gridExtra)
library(egg)
library(magrittr)
library(multipanelfigure)
library(grid)

#change working directory
setwd("~/R_Projects/Reproductive traits") 

#LOAD DATA
trait_data <- read_excel("Data/Trait_data_raw/Trait_data_final.xlsx",na = "NA")
#select just filled rows
trait_data_1 <- trait_data[1:1701,]
#filter data, select species with flower level info and capitulum
trait_filtered <- filter(trait_data_1, Info_level == "flower" |  Info_level == "capitulum")
levels(as.factor(trait_filtered$Info_level))
#select columns of interest
traits <- trait_filtered %>% select(Order_all,Family_all,Genus_all,Species_all,Breeding_system,IMPUTED_Compatibility,Autonomous_selfing_level,Autonomous_selfing_level_data_type,Autonomous_selfing_level_fruit_set,Flower_morphology,Flower_symmetry,Flowers_per_plant,Flowers_per_inflorescence,Floral_unit_width,Corolla_diameter_mean,Corolla_length_mean,STYLE_IMPUTED,OVULES_IMPUTED,life_form,lifespan,IMPUTED_plant_height_mean_m)
#Remove duplicated species
t <- traits[!duplicated(traits$Species_all), ]
#check structure of the data
str(t)
#remove cases where the species is NA 
t <- t[!is.na(t$Species_all), ]

str(t)
t_trial <- t[,c(5,6,7,9:21)]
str(t_trial)
cols <- c( "Breeding_system","IMPUTED_Compatibility", "Autonomous_selfing_level","Flower_morphology","Flower_symmetry", "life_form", "lifespan")

t_trial[cols] <- lapply(t_trial[cols], factor)  ## as.factor() could also be used

colnames(t_trial) <- c("Breeding system","Compatibility system","Selfing_level", "Quantitative selfing","Flower morphology","Flower symmetry",  "Flower/plant", "Flower/inflorescence", "Inflorescence width", "Flower width",  "Flower length",  "Style length", "Ovule number", "Life form","Life span", "Plant height")

str(t_trial$`Life form`)
t_trial$Selfing_level<- as.factor(t_trial$Selfing_level)
res.impute <- imputeFAMD(t_trial, ncp=3,threshold = 1e-06) 

  res.impute$completeObs$`Life form` <- as.character(res.impute$completeObs$`Life form`)

  res.impute$completeObs$`Life form`[res.impute$completeObs$`Life form`=="herb"] <- "Herb"
  res.impute$completeObs$`Life form`[res.impute$completeObs$`Life form`=="shrub"] <- "Shrub"
  res.impute$completeObs$`Life form`[res.impute$completeObs$`Life form`=="tree"] <- "Tree"
  res.impute$completeObs$`Life form`[res.impute$completeObs$`Life form`=="vine"] <- "Vine"

  res.impute$completeObs$`Life form` <- as.factor(res.impute$completeObs$`Life form`)


#from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
a <- fviz_pca_ind(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="none",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(14)], 
                pointshape = 19, pointsize = 1,axes.linetype=NA,title="",
                palette = c("#FDE725FF","#31688EFF","#440154FF", "#35B779FF"))+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Life form")+theme(strip.text.x = element_blank(),strip.background = element_rect(colour="white", fill="white"),legend.position=c(0.052,0.81),legend.title=element_text(size=5),legend.key.size = unit(0.5,"line"),legend.text = element_text(size = 4))+
  guides(color = guide_legend(override.aes = list(size=1.5)))+ylab("PC 2")+xlab("")

  res.impute$completeObs$`Compatibility system` <- as.character(res.impute$completeObs$`Compatibility system`)
 res.impute$completeObs$`Compatibility system` <-  gsub("Compatibility system_", "", res.impute$completeObs$`Compatibility system`)

 
res.impute$completeObs$`Compatibility system`[res.impute$completeObs$`Compatibility system`=="self_compatible"] <- "Self compatible"
res.impute$completeObs$`Compatibility system`[res.impute$completeObs$`Compatibility system`=="partially_self_compatible"] <- "Partially self compatible"
 res.impute$completeObs$`Compatibility system`[res.impute$completeObs$`Compatibility system`=="self_incompatible"] <- "Self incompatible"
 res.impute$completeObs$`Compatibility system`[res.impute$completeObs$`Compatibility system`=="monoecious"] <- "Monoecious"
  res.impute$completeObs$`Compatibility system`[res.impute$completeObs$`Compatibility system`=="dioecious"] <- "Dioecious"


res.impute$completeObs$`Compatibility system` <- factor(res.impute$completeObs$`Compatibility system`, levels = c("Self compatible", "Partially self compatible","Self incompatible", "Monoecious", "Dioecious"))

 
 #from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
b <- fviz_pca_ind(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(2)], 
                pointshape = 19, pointsize = 1,axes.linetype=NA,title="",
                palette = c("#FDE725FF","#31688EFF","#440154FF", "#35B779FF","#21908CFF"))+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Compatibility")+theme(strip.text.x = element_blank(),strip.background = element_rect(colour="white", fill="white"),legend.position=c(0.114,0.794),legend.title=element_text(size=5),legend.key.size = unit(0.5,"line"),legend.text = element_text(size = 4))+
  guides(color = guide_legend(override.aes = list(size=1.5)))+ylab("")+xlab("")



res.impute$completeObs$`Life span` <- as.character(res.impute$completeObs$`Life span`)
res.impute$completeObs$`Life span`[res.impute$completeObs$`Life span`=="annual"] <- "short_lived"
res.impute$completeObs$`Life span`[res.impute$completeObs$`Life span`=="biennial"] <- "short_lived"
res.impute$completeObs$`Life span`[res.impute$completeObs$`Life span`=="short_lived"] <- "Short lived"
res.impute$completeObs$`Life span`[res.impute$completeObs$`Life span`=="perennial"] <- "Perennial"

res.impute$completeObs$`Life span` <- as.factor(res.impute$completeObs$`Life span`)

 
 #from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
c <- fviz_pca_ind(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(15)], 
                pointshape = 19, pointsize = 1,axes.linetype=NA,title="",
                palette = c("#35B779FF","#FDE725FF"))+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Life span")+
theme(strip.text.x = element_blank(),strip.background = element_rect(colour="white", fill="white"),legend.position=c(0.07,0.855),legend.title=element_text(size=5),legend.key.size = unit(0.5,"line"),legend.text = element_text(size = 4))+
  guides(color = guide_legend(override.aes = list(size=1.5)))+ylab("PC 2")+xlab("")




res.impute$completeObs$`Flower symmetry` <- as.character(res.impute$completeObs$`Flower symmetry`)
res.impute$completeObs$`Flower symmetry`[res.impute$completeObs$`Flower symmetry`=="actinomorphic"] <- "Actinomorphic"
res.impute$completeObs$`Flower symmetry`[res.impute$completeObs$`Flower symmetry`=="zygomorphic"] <- "Zygomorphic"
res.impute$completeObs$`Flower symmetry` <- as.factor(res.impute$completeObs$`Flower symmetry`)


 #from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
d <- fviz_pca_ind(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="var",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(6)], 
                pointshape = 19, pointsize = 1,axes.linetype=NA,title="",
                palette = c("#35B779FF","#FDE725FF"))+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Symmetry")+
theme(strip.text.x = element_blank(),strip.background = element_rect(colour="white", fill="white"),legend.position=c(0.08,0.86),legend.title=element_text(size=5),legend.key.size = unit(0.5,"line"),legend.text = element_text(size = 4))+
  guides(color = guide_legend(override.aes = list(size=1.5)))+ylab("")+xlab("")


res.impute$completeObs$`Flower morphology` <- as.character(res.impute$completeObs$`Flower morphology`)
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="bowl"] <- "open"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="dish"] <- "open"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="exposed"] <- "open"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="spadix"] <- "spike"


res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="open"] <- "Open"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="brush"] <- "Brush"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="campanulate"] <- "Campanulate"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="capitulum"] <- "Capitulum"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="funnelform"] <- "Funnelform"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="papilionaceous"] <- "Papilionaceous"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="spike"] <- "Spike"
res.impute$completeObs$`Flower morphology`[res.impute$completeObs$`Flower morphology`=="tube"] <- "Tube"



res.impute$completeObs$`Flower morphology` <- as.factor(res.impute$completeObs$`Flower morphology`)


 #from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
e <- fviz_pca_ind(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="none",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(5)], 
                pointshape = 19, pointsize = 1,axes.linetype=NA,title="",
                palette = c("#440154FF", "#46337EFF", "#365C8DFF", "#277F8EFF", "#1FA187FF", "#4AC16DFF", "#9FDA3AFF", "#FDE725FF"))+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Flower shape")+
theme(strip.text.x = element_blank(),strip.background = element_rect(colour="white", fill="white"),legend.position=c(0.08,0.726),legend.title=element_text(size=5),legend.key.size = unit(0.5,"line"),legend.text = element_text(size = 4))+
  guides(color = guide_legend(override.aes = list(size=1.5)))+ylab("PC 2")+xlab("PC 1")


res.impute$completeObs$`Breeding system` <- as.character(res.impute$completeObs$`Breeding system`)
res.impute$completeObs$`Breeding system` <- gsub("Breeding system_","", res.impute$completeObs$`Breeding system`)
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="androdioecious"] <- "dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="androgynodioecious"] <- "dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="andromonoecious"] <- "monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="gynodioecious"] <- "dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="gynoecious"] <- "monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="gynomonoecious"] <- "monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="gynomonoecious"] <- "monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="monoecious_dioecious"] <- "monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="polygamo-dioecious"] <- "dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="protandrous"] <- "hermaphrodite"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="protogynous"] <- "hermaphrodite"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="subdioecious"] <- "dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="submonoecious"] <- "monoecious"
#Change levels to capital letters
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="monoecious"] <- "Monoecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="dioecious"] <- "Dioecious"
res.impute$completeObs$`Breeding system`[res.impute$completeObs$`Breeding system`=="hermaphrodite"] <- "Hermaphrodite"

res.impute$completeObs$`Breeding system` <- as.factor(res.impute$completeObs$`Breeding system`)


 #from http://www.zhuoyao.net/2019/11/08/principal-component-methods-in-r-practical-guide/
f <- fviz_pca_ind(prcomp(res.impute$completeObs[-c(414,480,482,634,705,1139),c(4,7,8,9,10,12,13,16)], scale=T), label="none",
              geom.ind = "point",alpha.ind = 1, col.ind=res.impute$completeObs[-c(414,480,482,634,705,1139),c(1)], 
                pointshape = 19, pointsize = 1,axes.linetype=NA,title="",
                palette = c("#440154FF", "#21908CFF", "#FDE725FF"))+xlim(-7, 10) + ylim (-8,8)+border()+labs(color="Breeding system")+
theme(strip.text.x = element_blank(),strip.background = element_rect(colour="white", fill="white"),legend.position=c(0.085,0.84),legend.title=element_text(size=5),legend.key.size = unit(0.5,"line"),legend.text = element_text(size = 4))+
  guides(color = guide_legend(override.aes = list(size=1.5)))+ylab("PC 2")+xlab("PC 1")
 #grid.arrange(p1, p5, p3, p4, nrow=2,ncol=2,top="Solanaceae")
grid.newpage()



 grid.draw(arrangeGrob(cbind(ggplotGrob(a),ggplotGrob(b)),cbind(ggplotGrob(c),ggplotGrob(d)),cbind(ggplotGrob(e),ggplotGrob(f)),nrow=3))
#mylegend
 dev.off()


```

